### PR TITLE
Update to 0.15.0

### PR DESCRIPTION
**Pull request by lbdreyer**
This PR:
* updates to the latest release of iris-grib
* Pins to python >= 3.6 as we have dropped Python 2 support as part of this release
* adds a few more names to the recipe-maintainer list

### CODE REVIEW

**Comment by lbdreyer** [comment]
@conda-forge-admin, please rerender

**Comment by lbdreyer** [comment]
conda-forge-admin, please add noarch: python

**Comment by lbdreyer** [comment]
Brilliant! Thanks for merging and fixing my recipe @ocefpaf !

**Comment by ocefpaf** [comment]
> Brilliant! Thanks for merging and fixing my recipe @ocefpaf !

Thank you for the PR!

**Pull request merged**
