### PR TITLE
Bump version retry

### PR DESCRIPTION
**Pull request by corinnebosley**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
The version was updated in #10 by the bot. This PR is to add @corinnebosley as a maintainer, no need to wait for the CIs to merge this.

**Comment by corinnebosley** [comment]
Right, cool.  Thanks @ocefpaf, that was pretty confusing but if it's done it's done.

**Comment by ocefpaf** [comment]
Sorry about the confusion. The auto-update bot send #10 before you sent #11 and I use a GitHub extension that merges a PR when it is successful, so I did not even see yours before it was too late.

I did ask you to re-submit your name as a maintainer b/c that was not in the bot's PR.

**Pull request merged**
